### PR TITLE
Remove and ignore build and inst/doc directories

### PR DESCRIPTION
**Pull request by agrueneberg**
This is a redo of #26. Turns out `build/vignette.rds` had some references to `inst/doc/BGLR-extdoc.pdf`, which is why the package installation failed as described in #27. Both `build` and `inst/doc` should not be under version control and have been removed and ignored.

This will remove the following `R CMD check` warning:
```
* creating vignettes ... OK
Warning: ‘inst/doc’ files
    ‘BGLR-extdoc.Rnw’, ‘BGLR-extdoc.pdf’
```

Sorry that I only saw that now.

### CODE REVIEW

**Comment by perpdgo** [comment]
The pdf contains the compiled vignettes and the RNW file is just the latex source code for generating the pdf. When you install from source you can request to regenerate the vignettes which generates the pdf with figures with higher quality. 

If I understand correctly, do you want to remove both files?

**Comment by agrueneberg** [comment]
Yes, `inst/doc/BGLR-extdoc.Rnw` is just a (currently outdated) copy of `vignettes/BGLR-extdoc.Rnw` and `inst/doc/BGLR-extdoc.pdf` is the compiled vignette. Both are generated during `R CMD build` and therefore there is no need to put them under version control.

**Comment by perpdgo** [comment]
I will delete inst/doc/BGLR-extdoc.Rnw and build/vignette.rds.
I will keep inst/doc/BGLR-extdoc.pdf for now to have a compiled version of the 
vignette in the git. Also, for example when installing the package from source and 
you do not have all the LaTeX packages that are used to build the documentation, still
you can install the package and have the vignette installed. This can be done by generating the
tarball as follows:

R CMD build --no-build-vignettes BGLR

**Comment by agrueneberg** [comment]
The compiled version of the vignette can be found on CRAN: https://cran.r-project.org/web/packages/BGLR/vignettes/BGLR-extdoc.pdf I think that's a more suitable place for compiled files than the source repository, but it's your decision.

**Pull request closed without merging**
